Gemfile:
  puppet_version: '>= 3.4.0'
Rakefile:
  strict_variables: false
  lint_disable_checks:
    - documentation
    - inherits_across_namespaces
spec/spec_helper.rb:
  default_facts:
    concat_basedir: /tmp/concat
    fqdn: maestro.acme.com
.travis.yml:
  exclude_puppet:
    - 3.3.0
    - 3.2.0
